server:
  port: 8080
  servlet:
    context-path: /houtai
   
helloWorld: 
  abc: 111spring Boot 正文
   
msyql:
   jdbcName: com.mysql.cj.jdbc.Driver
   dbUrl: jdbc:mysql://localhost:3306/db_book
   userName: root
   password: 123456
# https://www.dazhuanlan.com/2019/12/13/5df32795f2766/
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/abc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      master:
        url: jdbc:mysql://localhost:3307/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
      slave:
        url: jdbc:mysql://localhost:3308/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   servlet:
     multipart.max-file-size: 10MB
     multipart.max-request-size: 100MB  
   
# 上传文件总的最大值
# spring.servlet.multipart.max-request-size=10MB
# 单个文件的最大值
# spring.servlet.multipart.max-file-size=10MB
     
freemarker:
   suffix: .html
   template-loader-path: classpath:/templates/

fileweizhi:
  common:
    ## windows系统下访问路径 在更换开发目录后注意更好地址
    uploadWindow: E:\2021_java\examspring\uploadfiles\
    ## Linux系统下访问路径
    uploadLinux: /user/img/